name: Deploy to production

on:
  workflow_run:
    workflows: ["Staging pipeline"]
    types:
      - completed


permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
